---
- name: Setup workstation
  hosts: workstation
  connection: local
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  pre_tasks:
    - name: Update package cache
      tags: always
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "Fedora"

  roles:
    - workstation
