---
- name: Install ruby
  become_user: root
  ansible.builtin.dnf:
    state: "present"
    name:
      - ruby

- name: Check if cargo is installed
  ansible.builtin.command: cargo --version
  register: cargo_exists
  ignore_errors: true

- name: Download rust installer
  when: cargo_exists.rc != 0
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup-init.sh
    mode: "0755"
    force: true

- name: Run rust installer
  when: cargo_exists.rc != 0
  ansible.builtin.command: "/tmp/rustup-init.sh -y"

- name: Remove rust installer
  when: cargo_exists.rc != 0
  ansible.builtin.file:
    path: /tmp/rustup-init.sh
    state: absent
