---
- name: Install ruby
  ansible.builtin.dnf:
    state: "present"
    name:
      - ruby

- name: Check rust installed
  ansible.builtin.shell: "cargo -v"
  register: cargo_exists
  ignore_errors: true

- name: Download rust installer
  when: cargo_exists is failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: true
  tags:
    - rust

- name: install rust/cargo
  when: cargo_exists is failed
  ansible.builtin.shell: "/tmp/sh.rustup.rs -y"
  tags:
    - rust
