---
- name: Install ruby
  ansible.builtin.dnf:
    state: "present"
    name:
      - ruby

- name: Install rust
  when: cargo_exists is failed
  tags:
    - rust
  block:
    - name: Check if cargo is installed
      ansible.builtin.stat:
        path: /usr/local/bin/cargo  # Assuming this is the standard path
      register: cargo_stat
      ignore_errors: true

    - name: Download rust installer
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-init.sh
        mode: "0755"
        force: true
      when: not cargo_stat.stat.exists
      tags:
        - rust

    - name: Run rust installer
      ansible.builtin.command: "/tmp/rustup-init.sh -y"
      when: not cargo_stat.stat.exists
      tags:
        - rust
      args:
        creates: /usr/local/bin/cargo  # This prevents the command from running if cargo is already installed

    - name: Remove rust installer
      ansible.builtin.file:
        path: /tmp/rustup-init.sh
        state: absent
      when: not cargo_stat.stat.exists
      tags:
        - rust
